apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
    - http:
        paths:
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: dispatcher
                port:
                  number: 8080