apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: rustconsumer
  replicas: 2
  template:
    metadata:
      labels:
        app: rustconsumer
    spec:
      containers:
      - name: rustconsumer
        image: "{STABLE_REGISTRY}/consumer:dev"
        env:
          - name: PG_HOST
            value: postgres
          - name: PG_PORT
            value: "5432"
          - name: PG_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: PG_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_PASSWORD
          - name: PG_DBNAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
          - name: AMQP_HOST
            value: "rabbitmq"
          - name: AMQP_PORT
            value: "5672"
          - name: AMQP_USER
            value: "guest"
          - name: AMQP_PASSWORD
            value: "guest"
      #@ if ${STABLE_REGISTRY_AUTH}:
      imagePullSecrets:
        - name: registry-secret
      #@ end
