apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: goserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: "docker.local:5000/pipline-demo/server:dev"
        ports:
        - containerPort: 8080
        env:
          - name: PG_HOST
            value: postgres
          - name: PG_PORT
            value: "5432"
          - name: PG_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: PG_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_PASSWORD
          - name: PG_DBNAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
