apiVersion: v1
kind: Service
metadata:
  name: graphql
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30003
  selector:
    app: jsgraphql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
spec:
  selector:
    matchLabels:
      app: jsgraphql
  replicas: 2
  template:
    metadata:
      labels:
        app: jsgraphql
    spec:
      containers:
      - name: jsgraphql
        image: "{STABLE_REGISTRY}/graphql:dev"
        ports:
        - containerPort: 4000
        env:
          - name: PG_HOST
            value: postgres
          - name: PG_PORT
            value: "5432"
          - name: PG_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: PG_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_PASSWORD
          - name: PG_DBNAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
      #@ if ${STABLE_REGISTRY_AUTH}:
      imagePullSecrets:
        - name: registry-secret
      #@ end
