apiVersion: v1
kind: Service
metadata:
  name: dispatcher
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 30001
  selector:
    app: godispatcher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  selector:
    matchLabels:
      app: godispatcher
  replicas: 2
  template:
    metadata:
      labels:
        app: godispatcher
    spec:
      containers:
      - name: godispatcher
        image: "docker.local:5000/pipline-demo/dispatcher:dev"
        ports:
        - containerPort: 8080
        env:
          - name: PG_HOST
            value: postgres
          - name: PG_PORT
            value: "5432"
          - name: PG_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: PG_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_PASSWORD
          - name: PG_DBNAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
