apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
spec:
  selector:
    matchLabels:
      app: gosensor
  replicas: 5
  template:
    metadata:
      labels:
        app: gosensor
    spec:
      containers:
        - name: gosensor
          image: "{STABLE_REGISTRY}/sensor:dev"
          env:
            - name: DISPATCHER_HOST
              value: "dispatcher"
            - name: DISPATCHER_PORT
              value: "8080"
      #@ if ${STABLE_REGISTRY_AUTH}:
      imagePullSecrets:
        - name: registry-secret
      #@ end