apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sensor
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism : 2
      template:
        spec:
          containers:
          - name: sensor
            image: "docker.local:5000/pipline-demo/sensor:dev"
            env:
              - name: DISPATCHER_HOST
                value: "dispatcher"
              - name: DISPATCHER_PORT
                value: "8080"
          restartPolicy: Never
      backoffLimit: 4
