apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
    nodePort: 30002
  selector:
    app: nextjs-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nextjs-web
  replicas: 2
  template:
    metadata:
      labels:
        app: nextjs-web
    spec:
      containers:
      - name: nextjs-web
        image: "docker.local:5000/pipline-demo/web:dev"
        ports:
        - containerPort: 3000